jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines8907797987forAlphabeticalArraNumeralsandOtherSymbo$'

# DataBase Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OffCampus
    username: root
    password: gautam
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update